name: Generate PDF versions of Markdown documents

on:
  push:
    paths:
      - README.md

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            --pdf-engine=xelatex
            --output=README.pdf
            README.md
      - uses: actions/upload-artifact@master
        with:
          name: README.pdf
