name: Generate PDF versions of Markdown documents

on:
  push:
    paths:
      - README.md

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --pdf-engine=xelatex
            --output=output/result.pdf ${{ steps.files_list.outputs.files }}

      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
